# -*- coding: utf-8 -*-
"""blacklist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kkU4kkPRuc49bf5yBNaqGOjadPGxOvFb
"""

import pandas as pd
dataset = pd.read_csv("malicious_phish.csv")
blacklist = []
def add_to_blacklist(url):
    if url not in blacklist:
        blacklist.append(url)
for index, row in dataset.iterrows():
    url = row['url']
    label = row['type']
    if label != 'benign':
        add_to_blacklist(url)
csv_file_path = '/content/black_list.csv'
import csv
url_list = [url for url in blacklist if len(url) < 250]
with open(csv_file_path, 'w', newline='') as file:
    writer = csv.writer(file)
    for url in url_list:
        writer.writerow([url])
#from google.colab import files
#files.download(csv_file_path)